import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black text-center text-sm py-1 text-white">
          This is a page cloned using data with web scraper from{" "}
          <a
            className="text-blue-600 hover:underline"
            href="http://www.cinerama.com.pe/"
            target="_blank"
          >
            cinerama.com.pe
          </a>
        </div>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
